### ISSUE TITLE
Couldn't load plugin 'BitFlagRenderer' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by fwfichtner** [jakimowb/bit-flag-renderer#3]
This tool looks great, but I am unable to load it in the recent version with the following error:

```
ImportError: cannot import name 'QgsSettingsTree' from 'qgis.core' (/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/core/__init__.py) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/__init__.py", line 9, in classFactory
    from bitflagrenderer.plugin import BitFlagRendererPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/bitflagrenderer/plugin.py", line 22, in 
    from bitflagrenderer.gui.bitflagrendererdockwidget import BitFlagRendererDockWidget
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/bitflagrenderer/gui/bitflagrendererdockwidget.py", line 8, in 
    import bitflagrenderer.core.settings as settings
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/BitFlagRenderer/bitflagrenderer/core/settings.py", line 4, in 
    from qgis.core import QgsSettingsTree
ImportError: cannot import name 'QgsSettingsTree' from 'qgis.core' (/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/core/__init__.py)


Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.8-Firenze Firenze, 5ac45272b5 
```

**Comment by thielfab** [comment]
Can confirm this. Seems to be only related to the LTR 3.28. Plugin works on 3.34.
